#(hash) print("hello world!")
#print("hello")
#print("i like typing these")
#print("this is fun")
#print('yay! printing.')
#print("i would much rather you 'not'.")
#print('i "said" do not touch these.')
print("this is awesome!!")
