print(3+5*10/7)
print(4*8/2)
print("0000000000000000000000000000000000000000000000000000000000")
print("                        0000000000000                 ")
print("                           000000                        ")
print("                             000   ")
print("                              0")
print("                              0")
print("                              0")
print("                              0")
print("                              0")
print("                              0")
print("                              0")
print("                              0")
print("                              0")
print("                              0")
print("                              0")
print("                              0")
print("                              0")
print("                              0")
print("                              0")
print("                              0")
print("                              0")

print("      PLEASE USE PEDMAS RULR FOR PYTHON!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
print("                              AND      NOT BODMAS!!!!!!!!!!!!!!")
print("  please use only small case in python syntax")
